#!/usr/bin/env python3
"""Validate, stage, reconcile, and atomically publish a cleaned SPARCS CSV."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from medical_ai.config import get_settings
from medical_ai.db import MySQLExecutor
from medical_ai.pipeline.full_import import (
    FullDataImporter,
    ImportOptions,
    ImportPipelineError,
    SourceManifestError,
    default_audit_path,
    load_clean_source,
    new_import_task_id,
)

DEFAULT_CLEAN_CSV = ROOT / "data" / "processed" / "inpatient_sparcs_2021_clean.csv"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Load a verified cleaned SPARCS CSV into an isolated staging table "
            "and atomically publish it to MySQL."
        )
    )
    parser.add_argument("--csv", type=Path, default=DEFAULT_CLEAN_CSV)
    parser.add_argument(
        "--source-manifest",
        type=Path,
        default=None,
        help="Successful cleaning manifest; defaults to <csv>.manifest.json.",
    )
    parser.add_argument("--audit-output", type=Path, default=None)
    parser.add_argument(
        "--task-id", default=None, help="Optional UUID; a new UUID is generated by default."
    )
    parser.add_argument("--batch-size", type=int, default=5_000)
    parser.add_argument("--method", choices=["auto", "load-data", "insert"], default="auto")
    parser.add_argument(
        "--dry-run", action="store_true", help="Validate source and DB state without creating tables."
    )
    parser.add_argument(
        "--keep-failed-staging",
        action="store_true",
        help="Retain a failed staging table for an approved investigation.",
    )
    # These legacy flags are harmless compatibility aliases. They no longer
    # clear or drop the live table; every replacement uses staging + rename.
    parser.add_argument("--replace", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--replace-table", action="store_true", help=argparse.SUPPRESS)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        csv_path = args.csv.expanduser().resolve()
        task_id = args.task_id or new_import_task_id()
        manifest_path = (
            args.source_manifest.expanduser().resolve()
            if args.source_manifest is not None
            else csv_path.with_suffix(".manifest.json")
        )
        audit_path = (
            args.audit_output.expanduser().resolve()
            if args.audit_output is not None
            else default_audit_path(csv_path, task_id)
        )
        source = load_clean_source(
            csv_path,
            manifest_path=manifest_path,
        )
        options = ImportOptions(
            task_id=task_id,
            method=args.method,
            batch_size=args.batch_size,
            dry_run=args.dry_run,
            keep_backup=True,
            keep_failed_staging=args.keep_failed_staging,
        )
    except (SourceManifestError, ValueError) as exc:
        print(f"Import validation failed: {exc}", file=sys.stderr)
        return 2

    try:
        settings = get_settings()
        executor = MySQLExecutor(settings=settings)
        importer = FullDataImporter(executor.engine, settings)
    except Exception:
        print(
            "Import configuration failed; verify the protected environment settings.",
            file=sys.stderr,
        )
        return 2

    def report_progress(loaded_rows: int) -> None:
        if loaded_rows and loaded_rows % 100_000 == 0:
            print(f"committed {loaded_rows} staging rows", file=sys.stderr)

    try:
        result = importer.run(
            source,
            options,
            audit_path=audit_path,
            progress=report_progress,
        )
    except ImportPipelineError as exc:
        print(f"Import failed [{exc.code}]: {exc}", file=sys.stderr)
        print(f"Protected audit: {audit_path}", file=sys.stderr)
        return 1

    if result.status == "validated":
        print("Source manifest, cleaned CSV hash, and database state validated; no tables were changed.")
    else:
        print(
            f"Published {result.loaded_rows} rows with {result.method_used}; "
            f"previous live rows={result.live_rows_before}, new live rows={result.live_rows_after}."
        )
        if result.backup_table:
            print(f"Rollback table retained: {result.backup_table}")
    print(f"Audit: {result.audit_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
